title = 'ASI Cheetah3 configuration file'

[CHEETAH3]

    [CHEETAH3.misc]

        acquisition_timeout = 15000

    [CHEETAH3.connection]

        serverurl = 'http://10.35.44.20:8080'

    [CHEETAH3.scan]

        scan_engine = "Revolon"
        server_address = '10.35.44.20'
        server_port = 8088
        buffer_size = 64000


    [CHEETAH3.file_paths]

        bpc = ['/home/asi/bpc_00.bpc']
        dacs = ['/home/asi/dacs_00.dacs']
        data = ['/home/asi/']

    [CHEETAH3.destinations]

        [CHEETAH3.destinations.live_preview]

            [CHEETAH3.destinations.live_preview.Preview]

                SamplingMode = 'skipOnFrame'
                Period = 0.1
                ImageChannels = [
                    { Base = 'http://localhost:8082', Mode = 'count', Format = 'tiff'}
                ]

        [CHEETAH3.destinations.save_locally]

            Raw = [
                {Base = "file:/data/raw", FilePattern = "f%Hms_", SplitStrategy = "FRAME", QueueSize = 16384}
            ]

        [CHEETAH3.destinations.scan]

            Raw = [
                {Base = "tcp://connect@127.0.0.1:8098"}
            ]


        



